# Generated by Django 2.2.24 on 2021-11-22 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0002_profesor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'managed': False},
        ),
    ]
