# Generated by Django 2.2.24 on 2021-11-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0003_auto_20211122_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={},
        ),
    ]
