# Generated by Django 2.2.24 on 2021-11-08 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripción', models.CharField(max_length=1500)),
                ('entregada', models.BooleanField(default=False)),
                ('calificacion', models.FloatField(default=0.0)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('materia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='materias.Materia')),
            ],
        ),
    ]
