# Generated by Django 2.2.24 on 2021-11-08 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('acudiente', models.CharField(max_length=200)),
                ('correo_acudiente', models.CharField(max_length=100)),
                ('telefono_acudiente', models.CharField(max_length=30)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='instituciones.Institucion')),
            ],
        ),
    ]
