# Generated by Django 2.2.24 on 2021-11-22 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_estudiante_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'managed': False},
        ),
    ]
