# Generated by Django 2.2.24 on 2021-11-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0004_auto_20211123_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'managed': False},
        ),
    ]
