"""
Django settings for Escuela project.

Generated by 'django-admin startproject' using Django 2.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5t(kyrh%g*j4g=o2x_mtkluhkh*8va&px965(oc%p+c3wn-==k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'instituciones.apps.InstitucionesConfig',
    'profesor.apps.ProfesorConfig',
    'estudiante.apps.EstudianteConfig',
    'grupo.apps.GrupoConfig',
    'clase.apps.ClaseConfig',
    'materias.apps.MateriasConfig',
    'tareas.apps.TareasConfig',
    'rest_framework',
    'drf_yasg',
]     #'django.contrib.staticfiles',  # required for serving swagger ui's css/js files


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Escuela.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Escuela.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

"""


DATABASE = {
    "default": {
       "ENGINE": 'django_mongodb_engine',
       "NAME": 'akasha_db',
       "HOST": 'mongodb+srv://StarFiveTeam:666JyzE3nEK.UDx@akasha-db.cpnnt.mongodb.net/akasha_db?retryWrites=true&w=majority',
       "USER": 'StarFiveTeam',
       "PASSWORD": '666JyzE3nEK.UDx',
       "OPTIONS": "SCRAM-SHA-1",
    }
}

DATABASE = {
    "default": {
        "ENGINE": 'djongo',
        "CLIENT": {
           "name": 'akasha_db',
           "host": 'mongodb+srv://StarFiveTeam:666JyzE3nEK.UDx@akasha-db.cpnnt.mongodb.net/akasha_db',
           "username": 'StarFiveTeam',
           "password": '666JyzE3nEK.UDx',
           "authMechanism": "SCRAM-SHA-1",
        },
    }
}


"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.socrates'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'es-la'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5
} #IsAuthenticated, AllowAny}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.mailtrap.io'
EMAIL_HOST_USER = '5d1a9936087c9d'
EMAIL_HOST_PASSWORD = '741fb8c1b6068f'
EMAIL_PORT = '2525'

CELERY_BROKER_URL = 'amqp://guest:guest@127.0.0.1:5672/'